name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      DOCKER_USERNAME: ${{ secrets.docker_username }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
      TAG: ${{ github.run_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag thanhtunguet/az-react-native-android:$TAG
    - name: Login to DockerHub
      run: echo ${DOCKER_PASSWORD} | docker login docker.io -u ${DOCKER_USERNAME} --password-stdin
    - name: Push image to DockerHub
      run: |
        docker tag thanhtunguet/az-react-native-android:$TAG docker push thanhtunguet/az-react-native-android:latest
        docker push thanhtunguet/az-react-native-android:$TAG
        docker push thanhtunguet/az-react-native-android:latest
