name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        IMAGE: az-react-native-android:$(date +%s)
        REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: -|
        export IMAGE=az-react-native-android:$(date +%s)
        docker build . --file Dockerfile --tag $REGISTRY/$IMAGE
        docker push $REGISTRY/$IMAGE
