name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: -|
        export IMAGE=az-react-native-android:$(date +%s)
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_REGISTRY}}/$IMAGE
        docker push ${{secrets.DOCKER_REGISTRY}}/$IMAGE
